name: app_agendamento
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.1.1
  dio:
  pretty_dio_logger:
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable:
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8
  firebase_auth: ^4.16.0
  package_info_plus: ^8.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/icons/
    - assets/intro/
    - assets/social/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
